name: 'saas_revenue_ops'
version: '1.0.0'
config-version: 2

# Configuration des profils de connexion
profile: 'saas_revenue_profile'

# Dossiers sources
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Organisation des modèles (Architecture d'Entreprise Modern Data Stack)
models:
  saas_revenue_ops:
    staging:
      +materialized: view
    marts:
      +materialized: table